In [1]:
# импортируем библиотеку numpy
import numpy as np 

In [2]:
# создаем массив NumPy
a = np.array([1, 4, 5, 8], float)
print("массив NumPy:\n{}".format(a))

массив NumPy:
[1. 4. 5. 8.]


In [3]:
# выясняем тип объекта
type(a)

numpy.ndarray

In [4]:
# смотрим тип значений, хранящихся в массиве
a.dtype

dtype('float64')

In [5]:
# воспользуемся функцией np.asarray()
a = np.asarray([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [6]:
# создаем одномерный массив, состоящий из 5 нулей
Z = np.zeros(5)
Z

array([0., 0., 0., 0., 0.])

In [7]:
# создаем одномерный массив, состоящий из 5 единиц
O = np.ones(5)
O

array([1., 1., 1., 1., 1.])

In [8]:
# создаем единичную квадратную матрицу 3x3 (элементы 
# на главной диагонали равны 1, все остальные – 0)
E = np.eye(3)
E

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# создаем единичную квадратную матрицу 3x3 (элементы 
# на главной диагонали равны 1, все остальные – 0)
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# заполняем значения нулями
I.fill(0)
I

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# np.empty() не инициализирует элементы
np.empty(2)

array([2.05833592e-312, 2.33419537e-312])

In [12]:
# вернемся к массиву a
a

array([1., 4., 5., 8.])

In [13]:
# смотрим первые 2 элемента
a[:2]

array([1., 4.])

In [14]:
# смотрим элемент с индексом 3
# (индексация с 0)
a[3]

8.0

In [15]:
# присваиваем первому элементу (элементу 
# с индексом 0) значение 5.
a[0] = 5.
# смотрим результат
a

array([5., 4., 5., 8.])

In [16]:
# создаем двумерный массив
a = np.array([[1, 2, 3], 
              [4, 5, 6]], 
             float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
# обратимся к элементу c индексом 0 
# по оси строк и оси столбцов
a[0, 0]

1.0

In [18]:
# обратимся к элементу c индексом 0 по
# оси строк и индексом 1 по оси столбцов
a[0, 1]

2.0

In [19]:
# обращаемся ко второй строке
a[1,:]

array([4., 5., 6.])

In [20]:
# обращаемся к третьему столбцу
a[:, 2]

array([3., 6.])

In [21]:
# сначала отбираем последнюю строку
# и в ней отбираем значения по двум
# последним столбцам
a[-1:, -2:]

array([[5., 6.]])

In [22]:
# создаем массив a
a = np.array([1, 2, 3], float)
# присваиваем массиву a имя b
b = a
# создаем c - копию массива a
c = a.copy()
# первому элементу массива a 
# присваиваем значение 0
a[0] = 0

In [23]:
# смотрим массив b
b

array([0., 2., 3.])

In [24]:
# смотрим массив c
c

array([1., 2., 3.])

In [25]:
# смотрим информацию о количестве 
# строк и столбцов в массиве
a.shape

(3,)

In [26]:
# смотрим информацию о количестве 
# элементов массива
a.size

3

In [27]:
# смотрим размерность массива
a.ndim

1

In [28]:
# смотрим длину первой оси
len(a)

3

In [29]:
# проверяем, есть ли значение 2 в массиве
2 in a

True

In [30]:
# проверяем, есть ли значение 0 в массиве
0 in a

True

In [31]:
# создаем одномерный массив с 10 элементами 
a = np.array(range(10), float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [32]:
# превратим одномерный массив с 10 элементами 
# в двумерный массив, первая ось будет содержать 
# 5 элементов, а вторая ось – 2 элемента
a = np.reshape(a, (5, 2))
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [33]:
# преобразовываем обратно
a = np.reshape(a, 10)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
# снова превратим одномерный массив с 10 элементами 
# в двумерный массив, первая ось будет содержать 
# 5 элементов, а вторая ось – 2 элемента,
# только уже с помощью метода .reshape()
a = a.reshape((5, 2))
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [35]:
# создаем массив
a = np.array([1, 2, 3], float)
# преобразовываем в список 
# с помощью метода .tolist()
a.tolist()

[1.0, 2.0, 3.0]

In [36]:
# преобразовываем в список 
# с помощью функции list()
list(a)

[1.0, 2.0, 3.0]

In [37]:
# создаем массив
a = np.array([1, 2, 3], float)
# переводим массив в бинарную строку
s = a.tobytes()
# смотрим результат
s

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [38]:
# выполняем обратное преобразование
np.frombuffer(s)

array([1., 2., 3.])

In [39]:
# создаем массив из 6 элементов, 
# 2 строки и з столбца
a = np.array(range(6), float).reshape((2, 3))
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [40]:
# выполняем транспонирование, получаем 3 строки и 2 столбца
a_t = a.transpose()
# смотрим транспонированный массив
a_t

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [41]:
# можно покороче
a_T = a.T
a_T

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [42]:
# создаем многомерный массив
a = np.array([[1, 2, 3], 
              [4, 5, 6]], 
             float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [43]:
# преобразовываем многомерный массив в одномерный
a_f = a.flatten()
a_f

array([1., 2., 3., 4., 5., 6.])

In [44]:
# модифицируем выходной массив
a_f[0] = 0

# смотрим выходной и исходный массивы
print(a_f)
print("")
print(a)

[0. 2. 3. 4. 5. 6.]

[[1. 2. 3.]
 [4. 5. 6.]]


In [45]:
# преобразовываем многомерный массив в одномерный
a_r = np.ravel(a)
a_r

array([1., 2., 3., 4., 5., 6.])

In [46]:
# модифицируем выходной массив
a_r[0] = 0

# смотрим выходной и исходный массивы
print(a_r)
print("")
print(a)

[0. 2. 3. 4. 5. 6.]

[[0. 2. 3.]
 [4. 5. 6.]]


In [47]:
# создаем массивы для конкатенации
a = np.array([1, 2], float)
b = np.array([3, 4, 5, 6], float)
c = np.array([7, 8, 9], float)
# выполняем конкатенацию массивов, 
# создавая новый массив
d = np.concatenate((a, b, c))
# смотрим получившийся массив
d

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [48]:
# создаем массивы для конкатенации
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)
# выполняем конкатенацию массивов, создавая новый массив
# (по умолчанию выполняется конкатенация по оси строк)
c = np.concatenate((a,b))
# смотрим получившийся массив
c

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [49]:
# выполняем конкатенацию массивов 
# по оси строк, указав axis=0
c = np.concatenate((a, b), axis=0)
# смотрим получившийся массив
c

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [50]:
# выполняем конкатенацию массивов 
# по оси столбцов, указав axis=1
d = np.concatenate((a, b), axis=1)
# смотрим получившийся массив
d

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [51]:
# выполняем конкатенацию одномерных 
# массивов с помощью np.vstack()
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
c = np.vstack((a, b))
c

array([[1, 2, 3],
       [2, 3, 4]])

In [52]:
# конкатенируем двумерные массивы
# с помощью np.vstack()
a = np.array([[1, 2, 3], 
              [3, 4, 6]])
b = np.array([[2, 3, 4], 
              [5, 7, 1]])
c = np.vstack((a, b))
c

array([[1, 2, 3],
       [3, 4, 6],
       [2, 3, 4],
       [5, 7, 1]])

In [53]:
# выполняем конкатенацию одномерных массивов 
# с помощью np.row_stack()
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
c = np.row_stack((a, b))
c

array([[1, 2, 3],
       [2, 3, 4]])

In [54]:
# конкатенируем двумерные массивы
# с помощью np.row_stack()
a = np.array([[1, 2, 3], 
              [3, 4, 6]])
b = np.array([[2, 3, 4], 
              [5, 7, 1]])
c = np.row_stack((a, b))
c

array([[1, 2, 3],
       [3, 4, 6],
       [2, 3, 4],
       [5, 7, 1]])

In [55]:
# выполняем конкатенацию одномерных
# массивов с помощью np.hstack()
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
c = np.hstack((a, b))
c

array([1, 2, 3, 2, 3, 4])

In [56]:
# конкатенируем двумерные массивы
# с помощью np.hstack()
a = np.array([[1, 2, 3], 
              [3, 4, 6]])
b = np.array([[2, 3, 4], 
              [5, 7, 1]])
c = np.hstack((a, b))
c

array([[1, 2, 3, 2, 3, 4],
       [3, 4, 6, 5, 7, 1]])

In [57]:
# выполняем конкатенацию одномерных 
# массивов с помощью np.column_stack()
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
c = np.column_stack((a, b))
c

array([[1, 2],
       [2, 3],
       [3, 4]])

In [58]:
# конкатенируем двумерные массивы
# с помощью np.column_stack()
a = np.array([[1, 2, 3], 
              [3, 4, 6]])
b = np.array([[2, 3, 4], 
              [5, 7, 1]])
c = np.column_stack((a, b))
c

array([[1, 2, 3, 2, 3, 4],
       [3, 4, 6, 5, 7, 1]])

In [59]:
# создаем массивы для выполнения арифметических операций
a = np.array([1, 2, 3], float)
b = np.array([5, 2, 6], float)

In [60]:
# выполняем сложение
a + b

array([6., 4., 9.])

In [61]:
# выполняем вычитание
a - b

array([-4.,  0., -3.])

In [62]:
# выполняем умножение
a * b

array([ 5.,  4., 18.])

In [63]:
# выполняем деление
a / b

array([0.2, 1. , 0.5])

In [64]:
# выполняем возведение в степень
b ** a

array([  5.,   4., 216.])

In [65]:
# создаем массивы для выполнения арифметических операций
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[2, 0], [1, 3]], float)
# выполняем умножение
a * b

array([[ 2.,  0.],
       [ 3., 12.]])

In [66]:
# при несоответствии размеров массивов 
# выбрасываются ошибки
a = np.array([1, 2, 3], float)
b = np.array([4, 5], float)
a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [67]:
# создаем массивы, различающиеся по размерности
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)

In [68]:
# выполняем сложение
a + b

array([[0., 5.],
       [2., 7.],
       [4., 9.]])

In [69]:
# создаем массив
a = np.array([1, 4, 9], float)
# берем квадратный корень
np.sqrt(a)

array([1., 2., 3.])

In [70]:
# создаем массив
a = np.array([1.1, 1.5, 1.9], float)

In [71]:
# функция rint() округляет до ближайшего целого 
# числа по общепринятым правилам
np.rint(a)

array([1., 2., 2.])

In [72]:
# функция ceil() округляет до ближайшего целого, 
# но только всегда в большую сторону
np.ceil(a)

array([2., 2., 2.])

In [73]:
# функция floor() округляет до ближайшего целого, 
# но только всегда в меньшую сторону
np.floor(a)

array([1., 1., 1.])

In [74]:
# выведем число пи и e - основание натурального логарифма
print(np.pi)
print(np.e)

3.141592653589793
2.718281828459045


In [75]:
# создаем массив
a = np.array([2, 4, 3], float)

In [76]:
# суммируем
print(a.sum())
print(np.sum(a))

9.0
9.0


In [77]:
# перемножаем
print(a.prod())
print(np.prod(a))

24.0
24.0


In [78]:
# создаем массив
a = np.array([2, 1, 9], float)

In [79]:
# вычисляем среднее
print(a.mean())
print(np.mean(a))

4.0
4.0


In [80]:
# вычисляем стандартное отклонение
print(a.std())
print(np.std(a))

3.559026084010437
3.559026084010437


In [81]:
# вычисляем дисперсию
print(a.var())
print(np.var(a))

12.666666666666666
12.666666666666666


In [82]:
# находим минимум
print(a.min())
print(np.min(a))

1.0
1.0


In [83]:
# находим максимум
print(a.max())
print(np.max(a))

9.0
9.0


In [84]:
# находим индекс минимального элемента
np.argmin(a)

1

In [85]:
# находим индекс максимального элемента
np.argmax(a)

2

In [86]:
# создаем двумерный массив
a = np.array([[0, 2], 
              [3, -1], 
              [3, 5]], 
             float)
a

array([[ 0.,  2.],
       [ 3., -1.],
       [ 3.,  5.]])

In [87]:
# вычисляем среднее по оси строк (оси 0)
np.mean(a, axis=0)

array([2., 2.])

In [88]:
# вычисляем среднее по оси столбцов (оси 1)
np.mean(a, axis=1)

array([1., 1., 4.])

In [89]:
# вычисляем среднее по умолчанию
# эквивалентно np.mean(a, axis=None)
np.mean(a)

2.0

In [90]:
# создаем двумерный массив 
# c пропущенными значениями
a = np.array([[np.nan, 2, 4], 
              [9, 2, np.nan]], 
             float)
a

array([[nan,  2.,  4.],
       [ 9.,  2., nan]])

In [91]:
# вычисляем среднее по оси строк (оси 0)
np.nanmean(a, axis=0)

array([9., 2., 4.])

In [92]:
# вычисляем среднее по оси столбцов (оси 1)
np.nanmean(a, axis=1)

array([3. , 5.5])

In [93]:
# вычисляем среднее по умолчанию
# эквивалентно np.nanmean(a, axis=None)
np.nanmean(a)

4.25

In [94]:
# создаем двумерный массив 
# c пропущенными значениями
a = np.array([[np.nan, 2, 4], 
              [9, 2, np.nan]], 
             float)
# заменяем все пропуски значением 5
a = np.nan_to_num(a, nan=5)
a

array([[5., 2., 4.],
       [9., 2., 5.]])

In [95]:
a = np.array([[np.nan, 2, 4], 
              [9, 2, np.nan]], 
             float)
a

array([[nan,  2.,  4.],
       [ 9.,  2., nan]])

In [96]:
# заменяем пропуски в столбце с индексом 0
a = np.array([[np.nan, 2, 4], 
              [9, 2, np.nan]], 
             float)
a[:, 0] = np.nan_to_num(a[:, 0], nan=5)
a

array([[ 5.,  2.,  4.],
       [ 9.,  2., nan]])

In [97]:
# заменяем пропуски в строке с индексом 1
a = np.array([[np.nan, 2, 4], 
              [9, 2, np.nan]], 
             float)
a[1, :] = np.nan_to_num(a[1, :], nan=5)
a

array([[nan,  2.,  4.],
       [ 9.,  2.,  5.]])

In [98]:
# создаем массив с пропусками
a = np.array([[np.nan, 2, 4], 
              [9, np.nan, np.nan]], 
             float)
a

array([[nan,  2.,  4.],
       [ 9., nan, nan]])

In [99]:
# создаем словарь со значениями для замены
enc_dict = {0: 5, 1: 6, 2: 7}

# по каждому столбцу массива заменяем пропуски 
# значением из словаря
for col in range(a.shape[1]):
    a[:, col] = np.nan_to_num(a[:, col], 
                              nan=enc_dict[col])  
a

array([[5., 2., 4.],
       [9., 6., 7.]])

In [100]:
# создаем массив с пропусками
a = np.array([[np.nan, 2, 4], 
              [9, np.nan, np.nan]], 
             float)

# создаем словарь со значениями для замены
enc_dict = {0: 5, 1: 10}

# по каждой строке массива заменяем пропуски 
# значением из словаря
for col in range(a.shape[0]):
    a[col, :] = np.nan_to_num(a[col, :], 
                              nan=enc_dict[col])    
a

array([[ 5.,  2.,  4.],
       [ 9., 10., 10.]])

###  Функция np.linspace()

In [101]:
# создаем одномерный массив из 50 элементов, 
# значения которых равномерно распределены 
# внутри интервала от 0 до 1
np.linspace(start=0, stop=1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [102]:
# создаем массив из 6 элементов, значения которых равномерно 
# распределены внутри интервала от 1 до 6, 
# включаем/отключаем параметр endpoint
print(np.linspace(start=1, stop=6, num=6, endpoint=True))
print(np.linspace(start=1, stop=6, num=6, endpoint=False))

[1. 2. 3. 4. 5. 6.]
[1.         1.83333333 2.66666667 3.5        4.33333333 5.16666667]


###  Функция np.logspace()

In [103]:
# создадим одномерный массив из 20 элементов, значения которых равномерно 
# распределены по логарифмической шкале внутри интервала, стартовым 
# значением которого будет 10 в степени -1 (0,1), а последним 
# значением будет 10 в степени 1 (10)
np.logspace(start=-1, stop=1, num=20)

array([ 0.1       ,  0.1274275 ,  0.16237767,  0.20691381,  0.26366509,
        0.33598183,  0.42813324,  0.54555948,  0.6951928 ,  0.88586679,
        1.12883789,  1.43844989,  1.83298071,  2.33572147,  2.97635144,
        3.79269019,  4.83293024,  6.15848211,  7.8475997 , 10.        ])

###  Функция np.digitize()

In [104]:
# создаем массив
a = np.array([3, 9, 15], float)
a

array([ 3.,  9., 15.])

In [105]:
# создаем список с границами
lst_bin = [3, 9, 15]
# возвращаем индексы бинов, когда right=False
print(np.digitize(x=a, bins=lst_bin, right=False))
# возвращаем индексы бинов, когда right=True
print(np.digitize(x=a, bins=lst_bin, right=True))

[1 2 3]
[0 1 2]


###  Функция np.searchsorted()

In [106]:
# создаем массив
a = np.array([4, 10, 12, 14, 16, 16, 59, 72, 78, 86])
# находим индекс, в который должен быть вставлен элемент 13
np.searchsorted(a, 13)

3

In [107]:
# создаем массив
a = np.array([9, 3, 7, 8, 3, 7, 9])
# находим индекс, в который должен быть вставлен элемент 5
np.searchsorted(a, 5)

2

###  Функция np.bincount()

In [108]:
# создаем массив
a = np.array([0, 2, 2, 1, 1, 1])
# смотрим количество вхождений каждого значения
np.bincount(a)

array([1, 3, 2])

In [109]:
# создаем массив
a = np.array([0, 2, 5, 5])
# смотрим количество вхождений каждого значения
np.bincount(a)

array([1, 0, 1, 0, 0, 2])

###  Функция np.apply_along_axis()

In [110]:
# создаем массив NumPy
a = np.array([[0, 0, 0, 1], 
              [1, 1, 1, 0], 
              [0, 1, 1, 1], 
              [0, 1, 1, 0]])

In [111]:
# применяем  по оси строк функцию подсчета количества 
# вхождений значений, затем функцию поиска индекса 
# максимального элемента
np.apply_along_axis(lambda x: np.argmax(np.bincount(x)),
                    axis=0,
                    arr=a)

array([0, 1, 1, 0])

###  Функция np.insert()

In [112]:
# создаем массив
a = np.array([[0.1, 0.2, 0.5],
              [0.2, 0.7, 0.9],
              [1.3, 3.8, 2.2],
              [2.8, 1.5, 1.9]])

In [113]:
# создаем массив, который нужно добавить как строку
row = np.array([0.4, 0.7, 0.7])

In [114]:
# вставляем строку в конец массива
a = np.insert(a, 4, row, axis=0)
a

array([[0.1, 0.2, 0.5],
       [0.2, 0.7, 0.9],
       [1.3, 3.8, 2.2],
       [2.8, 1.5, 1.9],
       [0.4, 0.7, 0.7]])

In [115]:
# создаем массив, который нужно добавить как столбец
column = np.array([0, 1, 1, 0, 0])

In [116]:
# вставляем столбец в конец массива
a = np.insert(a, 3, column, axis=1)
a

array([[0.1, 0.2, 0.5, 0. ],
       [0.2, 0.7, 0.9, 1. ],
       [1.3, 3.8, 2.2, 1. ],
       [2.8, 1.5, 1.9, 0. ],
       [0.4, 0.7, 0.7, 0. ]])

###  Функция np.repeat()

In [117]:
# 4 раза повторяем элемент 3
np.repeat(3, 4)

array([3, 3, 3, 3])

In [118]:
# создаем двумерный массив
x = np.array([[1,2],
              [3,4]])
# два раза повторяем элементы
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [119]:
# три раза повторим элементы 
# двумерного массива по оси 0
np.repeat(x, 3, axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [120]:
# три раза повторим элементы 
# двумерного массива по оси 1
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

###  Функция np.unique()

In [121]:
# извлечем уникальные элементы
np.unique([1, 2, 2, 2, 3, 3, 3, 3, 3])

array([1, 2, 3])

In [122]:
# создаем массив
a = np.array([1, 2, 2, 2, 3, 3, 3, 3, 3])

# выведем частоты встречаемости уникальных элементов
values, counts = np.unique(a, return_counts=True)
dict(zip(values, counts))

{1: 1, 2: 3, 3: 5}

In [123]:
# получим массив индексов первых 
# вхождений уникальных элементов
_, indices = np.unique(a, return_index=True)
indices

array([0, 1, 4])

###  Функция np.take_along_axis()

In [124]:
# создаем массив X
np.random.seed(0)
X = np.round(np.random.rand(10, 10), 2)
X

array([[0.55, 0.72, 0.6 , 0.54, 0.42, 0.65, 0.44, 0.89, 0.96, 0.38],
       [0.79, 0.53, 0.57, 0.93, 0.07, 0.09, 0.02, 0.83, 0.78, 0.87],
       [0.98, 0.8 , 0.46, 0.78, 0.12, 0.64, 0.14, 0.94, 0.52, 0.41],
       [0.26, 0.77, 0.46, 0.57, 0.02, 0.62, 0.61, 0.62, 0.94, 0.68],
       [0.36, 0.44, 0.7 , 0.06, 0.67, 0.67, 0.21, 0.13, 0.32, 0.36],
       [0.57, 0.44, 0.99, 0.1 , 0.21, 0.16, 0.65, 0.25, 0.47, 0.24],
       [0.16, 0.11, 0.66, 0.14, 0.2 , 0.37, 0.82, 0.1 , 0.84, 0.1 ],
       [0.98, 0.47, 0.98, 0.6 , 0.74, 0.04, 0.28, 0.12, 0.3 , 0.12],
       [0.32, 0.41, 0.06, 0.69, 0.57, 0.27, 0.52, 0.09, 0.58, 0.93],
       [0.32, 0.67, 0.13, 0.72, 0.29, 0.18, 0.59, 0.02, 0.83, 0.  ]])

In [125]:
# получим отсортированные индексы по строке
order = X.argsort(axis=1)
order

array([[9, 4, 6, 3, 0, 2, 5, 1, 7, 8],
       [6, 4, 5, 1, 2, 8, 0, 7, 9, 3],
       [4, 6, 9, 2, 8, 5, 3, 1, 7, 0],
       [4, 0, 2, 3, 6, 5, 7, 9, 1, 8],
       [3, 7, 6, 8, 0, 9, 1, 4, 5, 2],
       [3, 5, 4, 9, 7, 1, 8, 0, 6, 2],
       [7, 9, 1, 3, 0, 4, 5, 2, 6, 8],
       [5, 7, 9, 6, 8, 1, 3, 4, 0, 2],
       [2, 7, 5, 0, 1, 6, 4, 8, 3, 9],
       [9, 7, 2, 5, 4, 0, 6, 1, 3, 8]])

In [126]:
# найдем топ 3 индексов 
top_idx = order[:, -3:][:, ::-1]
top_idx

array([[8, 7, 1],
       [3, 9, 7],
       [0, 7, 1],
       [8, 1, 9],
       [2, 5, 4],
       [2, 6, 0],
       [8, 6, 2],
       [2, 0, 4],
       [9, 3, 8],
       [8, 3, 1]])

In [127]:
# из каждой строки достанем 3 наибольших значения
top_k = np.take_along_axis(X, top_idx, axis=1)
top_k

array([[0.96, 0.89, 0.72],
       [0.93, 0.87, 0.83],
       [0.98, 0.94, 0.8 ],
       [0.94, 0.77, 0.68],
       [0.7 , 0.67, 0.67],
       [0.99, 0.65, 0.57],
       [0.84, 0.82, 0.66],
       [0.98, 0.98, 0.74],
       [0.93, 0.69, 0.58],
       [0.83, 0.72, 0.67]])

###  Функция np.array_split()

In [128]:
# импортируем Parallel и delayed для распараллеливания
from joblib import Parallel, delayed

In [129]:
# пишем медленную функцию
def slow_fn(x, n=5):
    """
    Медленная функция.
    
    Параметры
    ----------
    x: np.ndarray
        Массив значений.
    n: int
        Количество итераций 
        выполнения операции.
        
    Возвращает
    ----------
    results: np.ndarray
        Массив значений.
    """
    for i in range(n):
        np.random.seed(0)
        rnd = np.random.rand(*x.shape)
        x = x + rnd
        
    return x

# пишем функцию с распараллеливанием
def parallel_map(fn, x, n_jobs=4, *args, **kwargs):
    """
    Функция с распараллеливанием.
    
    Параметры
    ----------
    fn: callable
        Вызываемая функция.
    x: np.ndarray
        Входной массив.
    n_jobs: int
        Количество процессов.
    args: list
        Неименованные аргументы для 
        передачи в функцию.
    kwargs: dict
        Именованные аргументы для
        для передачи в функцию.

    Возвращает
    ----------
    results: np.ndarray
        Массив значений.
    """
    with Parallel(n_jobs) as p:
        res = p(delayed(fn)(part, *args, **kwargs) 
                for part in np.array_split(x, n_jobs))
    
    return np.concatenate(res)

In [130]:
# создаем массив
np.random.seed(0)
X = np.random.rand(100000, 100)

In [131]:
%%time

slow_fn(X, n=100)

CPU times: user 7.12 s, sys: 708 ms, total: 7.83 s
Wall time: 7.84 s


array([[ 55.4301639 ,  72.234126  ,  60.87910098, ...,   2.03086216,
         83.72294295,   0.4742431 ],
       [ 68.45947022,  27.27080529,  74.25459623, ...,  25.69000466,
          5.86094519,  43.87607918],
       [ 31.49138408,  70.33069237,  38.15293577, ...,  87.08134326,
         98.26486839,  97.04430046],
       ...,
       [100.58449943,  55.26692164,  97.40958124, ...,  97.61717411,
         86.8888155 ,  42.39754644],
       [ 27.53629179,   7.55992853,  92.99295104, ...,  68.78146004,
         34.7257013 ,   5.88385571],
       [ 66.54489318,  25.22817557,  49.20478964, ...,  70.86996313,
         46.07244422,  14.69914449]])

In [132]:
%%time

parallel_map(slow_fn, X, n_jobs=4, n=100)

CPU times: user 131 ms, sys: 191 ms, total: 322 ms
Wall time: 3.64 s


array([[ 55.4301639 ,  72.234126  ,  60.87910098, ...,   2.03086216,
         83.72294295,   0.4742431 ],
       [ 68.45947022,  27.27080529,  74.25459623, ...,  25.69000466,
          5.86094519,  43.87607918],
       [ 31.49138408,  70.33069237,  38.15293577, ...,  87.08134326,
         98.26486839,  97.04430046],
       ...,
       [ 31.76407696,  42.2681517 , 100.35156516, ...,  41.88772581,
         99.50098923,  49.18558749],
       [ 56.78399612,  25.69477427,  94.95402764, ...,  95.01045663,
          6.75348646,  23.41179416],
       [ 83.17514864,  31.92025962,  57.17805087, ...,  46.36804628,
         30.0120986 ,  74.90787463]])