In [1]:
# импортируем polars, pandas и numpy
import polars as pl
import pandas as pd
import numpy as np

# импортируем Parallel, delayed
from joblib import Parallel, delayed

# увеличиваем максмальное количество 
# отображаемых столбцов
pd.options.display.max_columns = 200

## In-place операции

In-place операции полезны для подсчета гистограмм. Допустим, есть массив целочисленных значений от 0 до 99, и мы хотим посчитать, сколько раз встречается каждое.

In [2]:
# случайный массив
arr = np.random.randint(0, 100, size=1000000)
# инициализируем гистограмму нулями
hist = np.zeros(100, dtype=np.int32)
# теперь inplace заполним ее
np.add.at(hist, arr, 1)
hist

array([ 9904, 10195, 10073,  9969,  9985,  9912, 10082, 10000,  9973,
       10031, 10106,  9931, 10010, 10100, 10089,  9982, 10086, 10078,
        9972, 10135, 10093, 10041, 10018,  9832,  9666,  9917, 10082,
        9824,  9961, 10080,  9920, 10006,  9888,  9831,  9908,  9889,
        9873, 10212, 10032,  9908, 10160, 10038, 10075,  9973,  9902,
       10001, 10003,  9809, 10008,  9994, 10154, 10127,  9908, 10059,
       10037, 10003,  9878, 10038,  9981,  9941,  9960, 10011, 10009,
       10049, 10130,  9979, 10018,  9818,  9882,  9933, 10058, 10141,
        9978,  9918, 10079, 10063,  9896, 10028,  9780,  9863, 10077,
       10229, 10106,  9975, 10007, 10079, 10056,  9890, 10031, 10181,
       10011, 10054,  9988,  9897, 10117, 10064,  9845,  9932, 10207,
        9978], dtype=int32)

можно с несколькими размерностями

In [3]:
arr0 = np.random.randint(0, 10, size=1000000)
arr1 = np.random.randint(0, 5, size=1000000)
# инициализируем гистограмму нулями
hist = np.zeros((10, 5), dtype=np.int32)
# теперь inplace заполним ее
np.add.at(hist, (arr0, arr1), 1)
hist

array([[20218, 20056, 19972, 19916, 19922],
       [20031, 20175, 19930, 19787, 19967],
       [20000, 20140, 20110, 19978, 20181],
       [19883, 19967, 20009, 20125, 20090],
       [20054, 19950, 20203, 20035, 20093],
       [20032, 20078, 19992, 20088, 20047],
       [20065, 20172, 19847, 19717, 19788],
       [19869, 19925, 20231, 20016, 19671],
       [19849, 19934, 20046, 19957, 20025],
       [19868, 20042, 20038, 19942, 19969]], dtype=int32)

можно не только считать, но и делать, например, groupby sum

In [4]:
arr0 = np.random.randint(0, 10, size=1000000)
arr1 = np.random.randint(0, 5, size=1000000)

x = np.random.rand(1000000)

hist = np.zeros((10, 5), dtype=np.float64)
# типа аналог x.groupby(arr0, arr1).sum()
np.add.at(hist, (arr0, arr1), x)
hist

array([[10116.1283585 , 10095.93284622,  9863.3618597 ,  9968.13282714,
        10073.84465794],
       [10032.81650577,  9900.46834809, 10000.79824479,  9949.830191  ,
         9949.12923472],
       [ 9871.97989648,  9897.95408647,  9892.07388805, 10017.37791632,
        10062.57709799],
       [10170.38737255,  9879.49308446,  9989.53851869,  9852.26282826,
         9991.87234051],
       [10015.61809185,  9932.71842797, 10003.54851251, 10026.63651438,
        10008.1755565 ],
       [10083.74114312,  9980.37116598, 10029.33230941, 10069.00008345,
         9841.82017977],
       [10143.06823263, 10053.14544029, 10133.85421869,  9999.41121828,
        10009.71240832],
       [ 9995.23653393, 10021.01648191,  9882.69919671, 10105.71580229,
        10082.87196282],
       [ 9872.75638489, 10087.57081407,  9970.10369584, 10067.38061677,
         9789.91259869],
       [10011.67038218, 10035.69420194,  9987.26771433,  9984.60515479,
         9951.10540039]])

## Fast target encoder

Попробуем сделать быстрый target encoder по кросс валидации с подбором регуляризации. Делать будем без циклов, используя бродкастинг и in-place операции

In [5]:
arr0 = np.array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0])
x = np.array([-5, 1, 10, 1, 3, 9, -2, -1, 7, 2])
fold = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])
print('Закодируем категорию {0} средним по {1}, используя кросс-валидацию {2}'.format(arr0, x, fold))

Закодируем категорию [0 1 2 0 1 2 0 1 2 0] средним по [-5  1 10  1  3  9 -2 -1  7  2], используя кросс-валидацию [0 0 0 0 0 1 1 1 1 1]


In [6]:
# посчитаем, сколько у нас категорий и фолдов
n_cats = arr0.max() + 1
n_folds = fold.max() + 1
n_cats, n_folds

(3, 2)

In [7]:
# для начала посчитаем x.groupby(fold, arr0,).sum()
f_sum = np.zeros((n_folds, n_cats), dtype=np.float64)
np.add.at(f_sum, (fold, arr0), x)
f_sum

array([[-4.,  4., 10.],
       [ 0., -1., 16.]])

In [8]:
# теперь x.groupby(fold, arr0).count()
f_count = np.zeros((n_folds, n_cats), dtype=np.float64)
np.add.at(f_count, (fold, arr0), 1)
f_count

array([[2., 2., 1.],
       [2., 1., 2.]])

In [9]:
# далее получим из этого x.groupby(arr0).sum() и x.groupby(arr0).count()
tot_sum = f_sum.sum(axis=0)
tot_count = f_count.sum(axis=0)
tot_sum, tot_count

(array([-4.,  3., 26.]), array([4., 3., 3.]))

In [10]:
# теперь посчитаем сумму и счетчик во всех фолдах, кроме текущего
# для этого из total суммы вычтем сумму groupby fold
# не забываем про бродкастинг. Тотал имеет 2 размерности (n_cats,), 
# а groupby fold - 3 (n_folds, n_cats)
oof_sum = tot_sum[np.newaxis, ...] - f_sum
print(oof_sum)
oof_count = tot_count[np.newaxis, ...] - f_count
print(oof_count)

[[ 0. -1. 16.]
 [-4.  4. 10.]]
[[2. 1. 2.]
 [2. 2. 1.]]


In [11]:
# к ним нужно добавить регуляризацию, по формуле:
# (y_sum + a * y_prior) / (y_count + a), a подберем так, 
# чтобы иметь среднеквадратичную наименьшую ошибку
# посчитаем prior
prior = tot_sum.sum() / tot_count.sum()
prior

2.5

In [12]:
# сетка регуляризации
grid = np.linspace(0.1, 10, 3)
grid

array([ 0.1 ,  5.05, 10.  ])

In [13]:
# применим наше кодирование с разными a по сетке grid, 
# для этого вспомним бродкастинг
# выходная размерность (x.shape[0], grid.shape[0])
enc_candidates = (oof_sum[fold, arr0, np.newaxis] + grid[np.newaxis, :] * prior) /\
    (oof_count[fold, arr0, np.newaxis] + grid[np.newaxis, :])
enc_candidates

array([[ 0.11904762,  1.79078014,  2.08333333],
       [-0.68181818,  1.9214876 ,  2.18181818],
       [ 7.73809524,  4.06028369,  3.41666667],
       [ 0.11904762,  1.79078014,  2.08333333],
       [-0.68181818,  1.9214876 ,  2.18181818],
       [ 9.31818182,  3.73966942,  3.18181818],
       [-1.78571429,  1.22340426,  1.75      ],
       [ 2.02380952,  2.35815603,  2.41666667],
       [ 9.31818182,  3.73966942,  3.18181818],
       [-1.78571429,  1.22340426,  1.75      ]])

In [14]:
# найдем лучшую a по сетке grid, тоже помним про бродкастинг
best_a = ((enc_candidates - x[:, np.newaxis]) ** 2).mean(axis=0).argmin()
best_a

0

In [15]:
# элемент с индексом best_a - лучший регуляризатор
best_oof_enc = enc_candidates[:, best_a]
best_oof_enc

array([ 0.11904762, -0.68181818,  7.73809524,  0.11904762, -0.68181818,
        9.31818182, -1.78571429,  2.02380952,  9.31818182, -1.78571429])

In [16]:
# теперь сохраним кодирование на тест
test_encoder = (tot_sum + prior * grid[best_a]) / (tot_count + grid[best_a])
test_encoder

array([-0.91463415,  1.0483871 ,  8.46774194])

In [17]:
# применим на тест
best_test_enc = test_encoder[arr0]
best_test_enc

array([-0.91463415,  1.0483871 ,  8.46774194, -0.91463415,  1.0483871 ,
        8.46774194, -0.91463415,  1.0483871 ,  8.46774194, -0.91463415])

## Parallel groupby

In [18]:
%%time

# для ускорения считываем файл в датафрейм polars,
# потом в датафрейм pandas, файл можно скачать по адресу
# https://www.kaggle.com/competitions/amex-default-prediction/data?select=train_data.csv
pandas_df = pl.read_csv('Data/train_data.csv', rechunk=False).to_pandas()

CPU times: user 1min 20s, sys: 1min 20s, total: 2min 41s
Wall time: 30.7 s


In [19]:
# взглянем на первые 5 наблюдений
pandas_df.head()

customer_ID         S_2       P_2  \
0  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-03-09  0.938469   
1  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-04-07  0.936665   
2  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-05-28  0.954180   
3  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-06-13  0.960384   
4  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...  2017-07-16  0.947248   

       D_39       B_1       B_2       R_1       S_3      D_41       B_3  D_42  \
0  0.001733  0.008724  1.006838  0.009228  0.124035  0.008771  0.004709   NaN   
1  0.005775  0.004923  1.000653  0.006151  0.126750  0.000798  0.002714   NaN   
2  0.091505  0.021655  1.009672  0.006815  0.123977  0.007598  0.009423   NaN   
3  0.002455  0.013683  1.002700  0.001373  0.117169  0.000685  0.005531   NaN   
4  0.002483  0.015193  1.000727  0.007605  0.117325  0.004653  0.009312   NaN   

   D_43      D_44       B_4      D_45       B_5       R_2      D_46      D_47  \
0   NaN  0.000630  0.080986  0.708906  0.170600  0.006204  0.358587  0.525351   
1   NaN  0.002526  0.069419  0.712795  0.113239  0.006206  0.353630  0.521311   
2   NaN  0.007605  0.068839  0.720884  0.060492  0.003259  0.334650  0.524568   
3   NaN  0.006406  0.055630  0.723997  0.166782  0.009918  0.323271  0.530929   
4   NaN  0.007731  0.038862  0.720619  0.143630  0.006667  0.231009  0.529305   

       D_48  D_49       B_6       B_7       B_8      D_50      D_51       B_9  \
0  0.255736  None  0.063902  0.059416  0.006466  0.148698  1.335856  0.008207   
1  0.223329  None  0.065261  0.057744  0.001614  0.149723  1.339794  0.008373   
2  0.189424  None  0.066982  0.056647  0.005126  0.151955  1.337179  0.009355   
3  0.135586  None  0.083720  0.049253  0.001418  0.151219  1.339909  0.006782   
4       NaN  None  0.075900  0.048918  0.001199  0.154026  1.341735  0.000519   

        R_3      D_52       P_3      B_10  D_53       S_5      B_11       S_6  \
0  0.001423  0.207334  0.736463  0.096219   NaN  0.023381  0.002768  0.008322   
1  0.001984  0.202778  0.720886  0.099804   NaN  0.030599  0.002749  0.002482   
2  0.007426  0.206629  0.738044  0.134073   NaN  0.048367  0.010077  0.000530   
3  0.003515  0.208214  0.741813  0.134437   NaN  0.030063  0.009667  0.000783   
4  0.001362  0.205468  0.691986  0.121518   NaN  0.054221  0.009484  0.006698   

       D_54       R_4       S_7      B_12       S_8      D_55      D_56  \
0  1.001519  0.008298  0.161345  0.148266  0.922998  0.354596  0.152025   
1  1.009033  0.005136  0.140951  0.143530  0.919414  0.326757  0.156201   
2  1.009184  0.006961  0.112229  0.137014  1.001977  0.304124  0.153795   
3  1.007456  0.008706  0.102838  0.129017  0.704016  0.275055  0.155772   
4  1.003738  0.003846  0.094311  0.129539  0.917133  0.231110  0.154914   

       B_13       R_5      D_58       S_9      B_14      D_59      D_60  \
0  0.118075  0.001882  0.158612  0.065728  0.018385  0.063646  0.199617   
1  0.118737  0.001610  0.148459  0.093935  0.013035  0.065501  0.151387   
2  0.114534  0.006328  0.139504  0.084757  0.056653  0.070607  0.305883   
3  0.120740  0.004980  0.138100  0.048382  0.012498  0.065926  0.273553   
4  0.095178  0.001653  0.126443  0.039259  0.027897  0.063697  0.233103   

       D_61      B_15      S_11      D_62 D_63 D_64      D_65      B_16  B_17  \
0  0.308233  0.016361  0.401619  0.091071   CR    O  0.007126  0.007665   NaN   
1  0.265026  0.017688  0.406326  0.086805   CR    O  0.002413  0.007148   NaN   
2  0.212165  0.063955  0.406768  0.094001   CR    O  0.001878  0.003636   NaN   
3  0.204300  0.022732  0.405175  0.094854   CR    O  0.005899  0.005896   NaN   
4  0.175655  0.031171  0.487460  0.093915   CR    O  0.009479  0.001714   NaN   

       B_18      B_19  D_66      B_20  D_68      S_12       R_6      S_13  \
0  0.652984  0.008520   NaN  0.004730   6.0  0.272008  0.008363  0.515222   
1  0.647093  0.002238   NaN  0.003879   6.0  0.188970  0.004030  0.509048   
2  0

In [20]:
# пишем обычную агрегирующую функцию
def slow_agg_fn(x, n=300):
    """
    Медленная агрегирующая функция
    
    Параметры
    ---------
    x: pandas.Series
        Серия значений.
   
    n: int
        Количество итераций 
        выполнения операции.
        
    Возвращает
    ----------
    results: pandas.Series
        
    """
    ser = x['P_2']
    for i in range(n):
        np.random.seed(0)
        rnd = np.random.rand(*ser.shape)
        ser = ser + rnd  
        
    return ser.mean()

def wrapper_fn(fn, grp, *args, **kwargs):   
    return grp[0], fn(grp[1], *args, **kwargs)


# пишем агрегирующую функцию с распараллеливанием
def parallel_aggregate(fn, df, by, cols, n_jobs=4, *args, **kwargs):
    """
    Агрегирующая функция с распараллеливанием.
    
    Параметры
    ----------
    fn: callable
        Вызываемая функция.
    df: pandas.DataFrame
        Датафрейм.
    by: list
        Список имен группирующих столбцов.
    cols, str
        Имя агрегируемого столбца.
    n_jobs: int
        Количество процессов.
    args: list
        Неименованные аргументы для 
        передачи в функцию.
    kwargs: dict
        Именованные аргументы для
        для передачи в функцию.
        
    Возвращает
    ----------
    results: pandas.Series
    """   
    res = {}
    groupby = df[by + cols].groupby(by)[cols]
    
    with Parallel(n_jobs) as p:
        res = p(delayed(wrapper_fn)(fn, grp, *args, **kwargs) for grp in groupby)
    
    res = pd.Series({x:y for (x, y) in res})
    
    return res

In [21]:
%%time

temp = pandas_df.groupby(['D_68', 'D_63'])[['P_2']].apply(slow_agg_fn)

CPU times: user 19.3 s, sys: 782 ms, total: 20.1 s
Wall time: 15.9 s


In [22]:
%%time

temp2 = parallel_aggregate(slow_agg_fn, pandas_df, ['D_68', 'D_63'], ['P_2'], n_jobs=8)

CPU times: user 845 ms, sys: 413 ms, total: 1.26 s
Wall time: 8.34 s
